apiVersion: batch/v1
kind: Job
metadata:
  name: job2
  namespace: negi
spec:
  completions: 10
  parallelism: 2
  template:
    metadata:
      name: job2-template
      namespace: negi
      labels:
        app: job2
    spec:
      containers:
        - name: job2
          image: python:3.9-slim
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          command:
            - "python"
            - "-c"
            - |
              import logging
              logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
              logging.info("Hello from Job2")
      restartPolicy: OnFailure
