apiVersion: batch/v1
kind: Job
metadata:
  name: job2
  namespace: negi
spec:
  completions: 10 # 完了する必要のあるジョブの数
  parallelism: 2  # 同時に実行するジョブの数
  template:
    metadata:
      labels:
        job: job2
    spec:
      containers:
        - name: job2
          image: python:3.9-slim
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          command:
            - "python"
            - "-c"
            - |
              import logging
              logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
              logging.info("Hello from App2")
      restartPolicy: OnFailure  # Jobが失敗した場合に再試行する設定
